package com.sys.model;
// Generated 10/10/2017 20:55:44 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Detallefactura generated by hbm2java
 */
public class Detallefactura  implements java.io.Serializable {


     private Integer idDetallefac;
     private Factura factura;
     private Producto producto;
     private String codigoBarras;
     private String nombreProducto;
     private int cantidad;
     private BigDecimal precioVenta;
     private BigDecimal total;

    public Detallefactura() {
    }

    public Detallefactura(Factura factura, Producto producto, String codigoBarras, String nombreProducto, int cantidad, BigDecimal precioVenta, BigDecimal total) {
       this.factura = factura;
       this.producto = producto;
       this.codigoBarras = codigoBarras;
       this.nombreProducto = nombreProducto;
       this.cantidad = cantidad;
       this.precioVenta = precioVenta;
       this.total = total;
    }
   
    public Integer getIdDetallefac() {
        return this.idDetallefac;
    }
    
    public void setIdDetallefac(Integer idDetallefac) {
        this.idDetallefac = idDetallefac;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public String getCodigoBarras() {
        return this.codigoBarras;
    }
    
    public void setCodigoBarras(String codigoBarras) {
        this.codigoBarras = codigoBarras;
    }
    public String getNombreProducto() {
        return this.nombreProducto;
    }
    
    public void setNombreProducto(String nombreProducto) {
        this.nombreProducto = nombreProducto;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getPrecioVenta() {
        return this.precioVenta;
    }
    
    public void setPrecioVenta(BigDecimal precioVenta) {
        this.precioVenta = precioVenta;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }




}


